services:
  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    image: cloudbeaver-adminer:6.0.1-mongodb
    container_name: adminer
    restart: unless-stopped
    network_mode: host
    command: ["php", "-S", "[::]:6868", "-t", "/var/www/html"]
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css:ro
      - ./adminer/adminer-dark.css:/var/www/html/adminer-dark.css:ro
      - ./adminer/plugins-enabled/menu-links.php:/var/www/html/plugins-enabled/menu-links.php:ro
      - ./adminer/plugins-enabled/brand-name.php:/var/www/html/plugins-enabled/brand-name.php:ro
      - ./adminer/plugins-enabled/default-pgsql.php:/var/www/html/plugins-enabled/default-pgsql.php:ro
      - ./adminer/plugins-enabled/mongo.php:/var/www/html/plugins-enabled/mongo.php:ro
      - ./adminer/plugins-enabled/redis.php:/var/www/html/plugins-enabled/redis.php:ro
      - ./adminer/plugins-enabled/login-ip.php:/var/www/html/plugins-enabled/login-ip.php:ro
      - ./adminer/plugins-enabled/cell-filter.php:/var/www/html/plugins-enabled/cell-filter.php:ro
      - ./adminer/plugins-enabled/row-num.php:/var/www/html/plugins-enabled/row-num.php:ro
      - ./adminer/plugins-enabled/select-shortcuts.php:/var/www/html/plugins-enabled/select-shortcuts.php:ro
      - ./adminer/plugins-enabled/select-searchable.php:/var/www/html/plugins-enabled/select-searchable.php:ro
      - ./adminer/plugins-enabled/select-limit-persist.php:/var/www/html/plugins-enabled/select-limit-persist.php:ro
      - ./adminer/plugins-enabled/theme-switcher.php:/var/www/html/plugins-enabled/theme-switcher.php:ro
      - ./adminer/plugins-enabled/table-style-switcher.php:/var/www/html/plugins-enabled/table-style-switcher.php:ro
      - ./adminer/plugins-enabled/row-highlight.php:/var/www/html/plugins-enabled/row-highlight.php:ro
      - ./adminer/plugins-enabled/select-check-ui.php:/var/www/html/plugins-enabled/select-check-ui.php:ro
      - ./adminer/plugins-enabled/select-smart-filter.php:/var/www/html/plugins-enabled/select-smart-filter.php:ro
      - ./adminer/plugins-enabled/select-row-inspector.php:/var/www/html/plugins-enabled/select-row-inspector.php:ro
      - ./adminer/plugins-enabled/select-autoapply.php:/var/www/html/plugins-enabled/select-autoapply.php:ro
      - ./adminer/plugins-enabled/menu-filter-fix.php:/var/www/html/plugins-enabled/menu-filter-fix.php:ro
      - ./adminer/plugins-enabled/select-toolbar-icons.php:/var/www/html/plugins-enabled/select-toolbar-icons.php:ro
      - ./adminer/plugins-enabled/structure-enum.php:/var/www/html/plugins-enabled/structure-enum.php:ro
      - ./adminer/plugins-enabled/select-json-edit.php:/var/www/html/plugins-enabled/select-json-edit.php:ro
      - ./adminer/plugins-enabled/auth-buttons.php:/var/www/html/plugins-enabled/auth-buttons.php:ro
      - ./adminer/plugins-enabled/select-sort-dir.php:/var/www/html/plugins-enabled/select-sort-dir.php:ro
      - ./adminer/plugins-enabled/sidebar-collapse.php:/var/www/html/plugins-enabled/sidebar-collapse.php:ro
      - ./adminer/plugins-enabled/connection-switcher.php:/var/www/html/plugins-enabled/connection-switcher.php:ro
      # - ./adminer/plugins-enabled/resize-menu.php:/var/www/html/plugins-enabled/resize-menu.php:ro
    environment:
      TZ: Asia/Ho_Chi_Minh
      ADMINER_DEFAULT_SERVER: localhost
      ADMINER_PLUGINS: >-
        dark-switcher
        tables-filter
        edit-foreign
        edit-textarea
        enum-option
        dump-json
        sql-log
